horizontal discount card
CodingHouseStudio/veteranam_info pull request #815
Opened 2024-11-25 13:51 UTC by MariiaMelnychenko

## Description

## Type of Change

- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🛠️ **Bug** fix (non-breaking change which fixes an issue)
- [ ] 🧪 **Test** - Adds or updates tests.
- [ ] ❌ **Breaking** change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 **Code refactor**
- [ ] ✅ **Build configuration change**
- [ ] 📝 **Documentation**
- [ ] 🗑️ **Chore**

2024-11-29 17:21 UTC, DemianKryk requested changes
Please see comments

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/extension/extension_dart_constants.dart
> +        return [];
Why did you change something here?

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/extension/extension_flutter_constants.dart
> +    final parts = [
I think we don't need to change this to list

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/extension/extension_flutter_constants.dart
> +        .replaceAll('\n', ' ');
Why did you remove \n?

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/city_list_widget.dart
> +      child: IntrinsicWidth(
can you check if this widget can be without IntrinsicWidth?

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/discount_text_widget.dart
> +        if (icon != null && button != null)
I think these values can't be null

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/discount_whom_granted_widget.dart
> +class Eligibility extends StatelessWidget {
Strange name for widget. I don't understand if I'll see this widget

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/discount_whom_granted_widget.dart
> +  final List<String> text;
I think you can use TrnslateModel here

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/discount_whom_granted_widget.dart
> +        return const Text(
I think it's strange to return here text widget. Better is String

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/drop_down_button_widget.dart
> +      position: PopupMenuPosition.under,
it's strange change

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +  late bool like;
it should be stateless widget

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +          onPressed: () {
it should be not enabled widget now

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +            onPressed: widget.share != null
how share can be null?

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +                      '$countLike',
countLike.toString()

2024-11-29 17:21 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +                padding: const EdgeInsets.only(left: KPadding.kPaddingSize36),
I think we can use here align

2024-11-29 17:35 UTC, DemianKryk commented on lib/shared/widget/discount_whom_granted_widget.dart
> +import 'package:flutter/gestures.dart';
rename this file

2024-12-02 10:21 UTC, MariiaMelnychenko commented on lib/shared/widget/city_list_widget.dart
> +      child: IntrinsicWidth(
I checked this widget can be without IntrinsicWidth

2024-12-02 10:22 UTC, DemianKryk commented on lib/shared/widget/city_list_widget.dart
> +      child: IntrinsicWidth(
Okay remove it because IntrinsicWidth is bad for parformence

2024-12-02 11:20 UTC, MariiaMelnychenko commented on lib/shared/widget/shared_icon_list_widget.dart
> +                padding: const EdgeInsets.only(left: KPadding.kPaddingSize36),
when I use Align the icon isn't aligned

2024-12-02 11:21 UTC, MariiaMelnychenko commented on lib/shared/extension/extension_dart_constants.dart
> +        return [];
I didn't change anything here, this is after merge

2024-12-03 17:35 UTC, DemianKryk requested changes
Please see comments

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/card_text_detail_evaluate_widget.dart
> +                    share: widget.share!,
Why do you add '!'?

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/city_list_widget.dart
> +        text: '${cityList.getCityString(
Why did you use '${, you can call this method without it

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +  Widget _getIconWidget(String text) {
use extension for this

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +  String _getLabelWidget(String text) {
use extension for this and we have translation in our app

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/drop_down_button_widget.dart
> +      tooltip: '',
why did you add this?

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/drop_down_button_widget.dart
> +            child: widget.discountButtons!
it call error if discountButtons will be null

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> -        if (link != null && link!.isUrlValid) ...[
why did you remove this 'if'?

2024-12-03 17:35 UTC, DemianKryk commented on lib/shared/widget/discount_card_widget.dart
>      return Container(
use ContrainedBox

2024-12-04 00:31 UTC, MariiaMelnychenko commented on lib/shared/widget/drop_down_button_widget.dart
> +      tooltip: '',
When you hover over the dropdownmenu button, the text "Show menu" appears in the center of the screen, and this line of code removes the pop-up menu.

2024-12-10 19:49 UTC, DemianKryk requested changes
Please, see comments

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/constants/dimensions/dimensions_constants.dart
> +  static const borderWidth = 3.0;
borderWidth3

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/extension/extension_flutter_constants.dart
> +      case EligibilityEnum.all: //TODO: спитати
|

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/city_list_widget.dart
>      return RichText(
I think better to use here Row With Text and TextButton

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_card_widget.dart
> +            IntrinsicHeight(
I think we can remove this widget when image is null or empty

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_card_widget.dart
> +          (discountItem.images != null && discountItem.images!.isNotEmpty)
Maybe better to add it to extension(we check empty and null both often)

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_card_widget.dart
> +          (discountItem.images != null && discountItem.images!.isNotEmpty)
For all the same expressions

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_card_widget.dart
> +      return Row(
I think we can use Text widget without Row when image is null or empty

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +    return RichText(
maybe better to use here Wrap

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/discount_text_widget.dart
> +  final List<EligibilityEnum>? text;
rename

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +        ? InkWell(
use IconButton

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +          padding: const EdgeInsets.all(KPadding.kPaddingSize5),
this padding broke exist logic, check login or filter popup button

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +  final DiscountModel? discountItem;
We can use this in another card please don't connect this widget only for one model

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +            Text(
it should the part of PopupMenuButtonWidget(user should be able to tap on this text and it'll open menu also)

2024-12-10 19:49 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +    return InkWell(
use Icon Button or Text Button

2024-12-10 19:49 UTC, DemianKryk commented on macos/Flutter/GeneratedPluginRegistrant.swift
> -import sqflite
not change this

2024-12-12 13:29 UTC, DemianKryk requested changes
Please, see comments

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/city_list_widget.dart
> +    return Row(
I think here better use wrap, because now this widget ca be overflow

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +      widgets.add(
Use addAll

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +        GestureDetector(
Don't use gesture detector

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +    this.iconButton = false,
I think this options is useless

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +            ? InkWell(
Use texbutton.icon

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +                      child: IconButton(
It's strange use button inside button

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +            : DecoratedBox(
Use button style

2024-12-12 13:29 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +            child: Row(
Not use if icon null

2024-12-13 09:14 UTC, MariiaMelnychenko commented on lib/shared/widget/popup_menu_button_widget.dart
> +    this.iconButton = false,
Why is this useless? It is needed when you just need an icon, not text

2024-12-13 10:54 UTC, DemianKryk approved these changes

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/extension/extension_flutter_constants.dart
> +          .replaceAll('**', '')
you can remove it

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/extension/extension_flutter_constants.dart
> +    if (images != null && images!.isNotEmpty) {
return images != null && images!.isNotEmpty

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/models/convertors/images_convertor.dart
> +    return object
use List.generate

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +    this.iconButton = false,
You can check it use icon, if it null not show icon

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +            ? TextButton.icon(
You can remove icon from here(you don't use icon option here)

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/widget/popup_menu_button_widget.dart
> +                    const DecoratedBox(
Use icon widget

2024-12-13 10:54 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +        Column(
remove it

2024-12-13 10:54 UTC, DemianKryk commented on macos/Flutter/GeneratedPluginRegistrant.swift
> -import sqflite
?

2024-12-13 11:11 UTC, DemianKryk approved these changes

2024-12-13 11:18 UTC, merged