fix: Horizontal discount card
CodingHouseStudio/veteranam_info pull request #844
Opened 2024-12-16 14:40 UTC by MariiaMelnychenko

## Description

## Type of Change

- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🛠️ **Bug** fix (non-breaking change which fixes an issue)
- [ ] 🧪 **Test** - Adds or updates tests.
- [ ] ❌ **Breaking** change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 **Code refactor**
- [ ] ✅ **Build configuration change**
- [ ] 📝 **Documentation**
- [ ] 🗑️ **Chore**

2024-12-16 14:49 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +        ..removeAt(0)
I think is better not create list for modifiableEligibility before it and you can use EligibilityEnum.valuesWithoutAll for this list

2024-12-16 14:52 UTC, MariiaMelnychenko commented on lib/shared/widget/discount_card_widget.dart
> +                          children: [
so that the discount looks the same on a tablet as it does on a desktop, without this parameter it is stretched

2024-12-16 20:04 UTC, DemianKryk requested changes
Please see comments

2024-12-16 20:04 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +              ...(EligibilityEnum.valuesWithoutAll.length > 5 && !showFullList
strange logic

2024-12-16 20:04 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +              ...(EligibilityEnum.valuesWithoutAll.length > 5 && !showFullList
Why did you separate two the same widget I wrote another please read my comment clearly. I didn't write to remove variable

2024-12-16 20:04 UTC, DemianKryk commented on lib/shared/widget/shared_icon_list_widget.dart
> +    return TextButton(
Why did you change this code?

2024-12-16 20:04 UTC, DemianKryk commented on macos/Flutter/GeneratedPluginRegistrant.swift
> +import sqflite
I think we can change it because we not use this platform and if we need we can change this free. Not worry about this changes at all

2024-12-17 14:41 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +              ...(EligibilityEnum.valuesWithoutAll.length > 5 && !showFullList
I add change for all state in EligibilityEnum to the main please merge

2024-12-17 14:41 UTC, DemianKryk commented on lib/shared/widget/discount_eligibility_widget.dart
> +              ...(EligibilityEnum.valuesWithoutAll.length > 5 && !showFullList
I add change for all state in EligibilityEnum to the main please merge

2024-12-19 07:00 UTC, MariiaMelnychenko commented on lib/components/discounts/widget/body/discounts_body_widget.dart
> +                        isDesk: isTablet,
so that the discount looks the same on a tablet as it does on a desktop, without this parameter it is stretched

2024-12-19 09:09 UTC, DemianKryk approved these changes

2024-12-19 09:09 UTC, merged